name: booknote
description: Take book notes.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core
  cupertino_icons: ^0.1.3

  # Helpers
  # app icon installer:
  flutter_launcher_icons: ^0.7.5
  # custom icons:
  font_awesome_flutter: ^8.8.1
  # free network fonts:
  google_fonts: ^1.1.0
  # automatic tool for resizing text:
  auto_size_text: ^2.1.0
  # custom spinners:
  flutter_spinkit: ^4.1.2+1
  # upload images to the app
  image_picker: ^0.6.7+7
  # webview for Editor
  webview_flutter: ^0.3.22+1
  # Zefyr (Note Editor)
  zefyr: ^0.11.0

  # State Management
  # provider:
  provider: ^4.1.3
  # bloc + cubit:
  flutter_bloc: ^6.0.5

  # Firebase
  # authentication:
  firebase_auth: ^0.16.1
  # database:
  cloud_firestore: ^0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# app icon installer configuration:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"

flutter:

  uses-material-design: true
  assets:
    - images/samples/
    - images/
    - files/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf

